version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:cached
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated
    env_file:
      - ./.env.db

  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "5050:80"
    environment:
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 600
    logging:
      driver: 'none'
    volumes:
      - pgadmindata:/var/lib/pgadmin:delegated
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  dbdata:
  pgadmindata: